[package]
name = "macremote"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "=0.5.0-rc.3"
tokio = { version = "1", features = ["full"] }

[[bin]]
name = "mac-remote"
path = "src/main.rs"
